#!/usr/bin/env python3
from __future__ import annotations
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
RESULTS = ROOT / "results"
RESULTS.mkdir(exist_ok=True)


def cmd(command: list[str]) -> str:
    try:
        return subprocess.check_output(command, text=True, stderr=subprocess.STDOUT).strip()
    except Exception as exc:
        return f"unavailable: {exc}"


def sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_pnr(text: str) -> dict[str, object]:
    out: dict[str, object] = {}
    patterns = {
        "slices_used": r"TRELLIS_SLICE:\s*(\d+)/(\d+)",
        "ebr_used": r"DP16KD:\s*(\d+)/(\d+)",
        "mult18_used": r"MULT18X18D:\s*(\d+)/(\d+)",
        "pll_used": r"EHXPLLL:\s*(\d+)/(\d+)",
    }
    for key, pattern in patterns.items():
        m = re.search(pattern, text)
        if m:
            out[key] = {"used": int(m.group(1)), "available": int(m.group(2))}
    m = re.search(r"Max frequency for clock .*?:\s*([0-9.]+) MHz", text)
    if m:
        out["max_frequency_mhz"] = float(m.group(1))
    out["timing_pass_25mhz"] = "PASS at 25.00 MHz" in text or "PASS at 25 MHz" in text
    return out


def main() -> None:
    pnr_log = (BUILD / "nextpnr.log").read_text(errors="replace") if (BUILD / "nextpnr.log").exists() else ""
    sim_log = (BUILD / "simulation.log").read_text(errors="replace") if (BUILD / "simulation.log").exists() else ""
    manifest = {
        "design": "RV32 TinyLLM SoC for ULX3S-85F",
        "target": {"fpga": "Lattice ECP5 LFE5U-85F-6BG381C", "board": "ULX3S v2.x/v3.0.x", "clock_mhz": 25},
        "cpu": {"core": "PicoRV32", "isa": "RV32I", "pinned_commit": "a473fc8fca393771d83b0ffcf0b14db3393339d8"},
        "accelerator": {"operations": ["INT8 GEMV", "packed signed INT4 GEMV"], "m_max": 2, "k_max": 8, "lanes": 4, "accumulator_bits": 32, "mmio_base": "0x10000000"},
        "verification": {"cpu_firmware_simulation_pass": "PASS: RV32 firmware completed INT8 and INT4 accelerator tests" in sim_log, "simulation_log_sha256": sha256(BUILD / "simulation.log")},
        "physical_implementation": parse_pnr(pnr_log),
        "artifacts": {
            "bitstream": "build/rv32_llm_soc_ulx3s_85f.bit",
            "bitstream_sha256": sha256(BUILD / "rv32_llm_soc_ulx3s_85f.bit"),
            "placed_routed_config_sha256": sha256(BUILD / "ulx3s.config"),
            "netlist_json_sha256": sha256(BUILD / "ulx3s.json"),
            "firmware_elf_sha256": sha256(BUILD / "firmware.elf")
        },
        "tool_versions": {
            "yosys": cmd(["yosys", "-V"]),
            "nextpnr_ecp5": cmd(["nextpnr-ecp5", "--version"]),
            "ecppack": cmd(["ecppack", "--version"]),
            "iverilog": cmd(["iverilog", "-V"]).splitlines()[0],
            "verilator": cmd(["verilator", "--version"]),
            "riscv_gcc": cmd(["riscv64-unknown-elf-gcc", "--version"]).splitlines()[0]
        },
        "honesty": {"fpga_board_programmed_in_ci": False, "silicon_tapeout_completed": False, "claim": "Bitstream is generated by synthesis and place-and-route; physical board execution requires the user to program an ULX3S-85F."}
    }
    (RESULTS / "build_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
